/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
//import javax.print.attribute.HashPrintRequestAttributeSet;
//import javax.print.attribute.PrintRequestAttributeSet;
//import javax.swing.*;

//import java.awt.*;
//import java.awt.event.*;

//import javax.swing.event.*;

//import java.awt.print.*;

//import javax.swing.border.*;
public class BillingSystem extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	//declaration of variable for phone
    double samsongGalaxy;
    double appleIphone;
    double sonyPhone;
    double lgPhone;
    double nokiaLumia;
    int quantity, quantity1, quantity2, quantity3, quantity4;
    double amount, amount1, amount2, amount3, amount4, subTotal, total, fTotal;
    double tax;
    double discount;


    /**
     * Creates new form BillingSystem
     */
    public BillingSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtRef = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jtxtSecondName = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtPhone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAddress = new javax.swing.JTextArea();
        jtxtGender = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jcmbSamsonQuantity = new javax.swing.JComboBox();
        jcmbSamsong = new javax.swing.JComboBox();
        jchcSamsong = new javax.swing.JCheckBox();
        jchcApple = new javax.swing.JCheckBox();
        jcmbApple = new javax.swing.JComboBox();
        jcmbAppleQuantity = new javax.swing.JComboBox();
        jcmbNokiaQuantity = new javax.swing.JComboBox();
        jcmbNokia = new javax.swing.JComboBox();
        jchcNokia = new javax.swing.JCheckBox();
        jchcSony = new javax.swing.JCheckBox();
        jchcLG = new javax.swing.JCheckBox();
        jcmbLG = new javax.swing.JComboBox();
        jcmbSony = new javax.swing.JComboBox();
        jcmbSonyQuantity = new javax.swing.JComboBox();
        jcmbLgQuantity = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jchcDiscount = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtDiscount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ref No:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("First Name:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Second Name:");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gender:");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email:");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Phone Number:");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Home Adress:");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtxtName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtxtSecondName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtxtPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtxtAddress.setColumns(20);
        jtxtAddress.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jtxtAddress.setRows(5);
        jScrollPane1.setViewportView(jtxtAddress);

        jtxtGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERSONAL INFORMATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtRef)
                            .addComponent(jtxtName)
                            .addComponent(jtxtSecondName)
                            .addComponent(jtxtEmail)
                            .addComponent(jtxtPhone)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(jtxtGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtxtRef, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MOBILE PHONE INFORMTION");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("MOBILE PHONE ");
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 255), new java.awt.Color(255, 255, 51)));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MODEL");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 0)));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("QUANTITY");
        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 0, 51)));

        jcmbSamsonQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbSamsonQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jcmbSamsong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcmbSamsong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Samsong Galaxy S5 SM-G900F", "Samsong Galaxy S6 SM-G920F", "Samsong Galaxy Note5 SM-G9201", "Samsong Galaxy S6 Edge", "Samsong Galaxy J5 SM-J500F", "Samsong Galaxy J2 SM-J200Y", "Samsong Galaxy Note4 SM-N910F", "Samsong Galaxy A3 SM-A300F", "Samsong Galaxy J1 Ace", "Samsong Galaxy A5 SM-A500F" }));

        jchcSamsong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jchcSamsong.setText("Samsong_Galaxy");

        jchcApple.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jchcApple.setText("Apple_iphone");
        jchcApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchcAppleActionPerformed(evt);
            }
        });

        jcmbApple.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcmbApple.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apple iphone 5s 16GB", "Apple iphone 6s 64GB", "Apple iphone 5s 32GB", "Apple iphone 6 16GB", "Apple iphone 6s Plus 64GB", "Apple iphone 6 64GB", "Apple iphone 6s 16GB", "Apple iphone 5c 16GB", "Apple iphone 6s 128GB", "Apple iphone Plus 16GB", " " }));

        jcmbAppleQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbAppleQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jcmbNokiaQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbNokiaQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jcmbNokia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcmbNokia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nokia Lumia 530", "Nokia Lumia 635", "Nokia Lumia 930", "Nokia Lumia 1020" }));

        jchcNokia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jchcNokia.setText("Nokia_Lumia");

        jchcSony.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jchcSony.setText("Sony_Xperia");

        jchcLG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jchcLG.setText("LG_Phone");

        jcmbLG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcmbLG.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LG G4 H815 Leather", "LG G3 D855", "LG G4 H815", "LG G3 SD722", "LG G4 Beat Dual H736P", "LG G2 D802 16GB", "LG V10 H962" }));

        jcmbSony.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcmbSony.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sony Xperia E4 E2105", "Sony Xperia Z5 Premium", "Sony Xperia E4 E2104", "Sony Xperia 5 Dual E6683", "Sony Xperia E4g E2003", "Sony Xperia M4 Aqua" }));

        jcmbSonyQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbSonyQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jcmbLgQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbLgQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jchcSony)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcmbSony, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jchcLG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcmbLG, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jchcNokia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcmbNokia, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jchcApple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(jcmbApple, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jcmbLgQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcmbNokiaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcmbSonyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcmbAppleQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jchcSamsong)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcmbSamsong, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcmbSamsonQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel23)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbApple, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchcApple)
                    .addComponent(jcmbAppleQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbNokia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchcNokia)
                    .addComponent(jcmbNokiaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbSony, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchcSony)
                    .addComponent(jcmbSonyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbLG, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchcLG)
                    .addComponent(jcmbLgQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcmbSamsong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcmbSamsonQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jchcSamsong))
                    .addContainerGap(265, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jchcDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jchcDiscount.setText("Customer Discount");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Discount");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 51, 0), new java.awt.Color(255, 255, 0)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sub Total");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 51), new java.awt.Color(204, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tax");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 0), new java.awt.Color(255, 255, 0)));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total");
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 0), new java.awt.Color(255, 255, 0)));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jtxtDiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchcDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtTax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jtxtSubTotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTotal)
                            .addComponent(jtxtDiscount, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jchcDiscount)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jtxtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel15.setBackground(new java.awt.Color(204, 0, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("GLOBAL MOBILE PHONE POINT OF SALE SYSTEM");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("TOTAL");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 255, 0), new java.awt.Color(102, 255, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("RESET");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 255, 0), new java.awt.Color(0, 255, 255), new java.awt.Color(0, 51, 204)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 102), new java.awt.Color(255, 255, 0), new java.awt.Color(0, 102, 255), new java.awt.Color(51, 255, 255)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane2.setViewportView(jtxtReceipt);

        jTabbedPane2.addTab("Receipt", jScrollPane2);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("PRINT");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 0), new java.awt.Color(255, 153, 153), new java.awt.Color(204, 0, 0), new java.awt.Color(0, 51, 255)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerform(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(273, 273, 273))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jchcAppleActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jtxtRef.setText(null);
        jtxtSecondName.setText(null);
        jtxtName.setText(null);
        jtxtAddress.setText(null);
        //jtxtAddress.setText(null);
        jtxtPhone.setText(null);
        jtxtEmail.setText(null);
        jtxtDiscount.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTax.setText(null);
        jtxtTotal.setText(null);
        jtxtReceipt.setText(null);
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String selectedText = (String)jcmbSamsong.getSelectedItem();
      String quantitySelected = (String)jcmbSamsonQuantity.getSelectedItem();
      quantity = Integer.parseInt(quantitySelected);
     
      if (jchcSamsong.isSelected()&&selectedText.equals("Samsong Galaxy S5 SM-G900F")){
            samsongGalaxy = 409.00;
            amount = samsongGalaxy * quantity;
      }
      else if (jchcSamsong.isSelected()&&selectedText.equals("Samsong Galaxy S6 SM-G920F")){
            samsongGalaxy = 679.00;
            amount = samsongGalaxy * quantity;
      }
      else if (jchcSamsong.isSelected()&&selectedText.equals("Samsong Galaxy Note5 SM-G9201")){
            samsongGalaxy = 884.00;
            amount = samsongGalaxy * quantity;
      }
      else if (jchcSamsong.isSelected()&&selectedText.equals("Samsong Galaxy S6 Edge")){
            samsongGalaxy = 820.00;
            amount = samsongGalaxy * quantity;
      }
      else if (jchcSamsong.isSelected()&&selectedText.equals("Samsong Galaxy J5 SM-J500F")){
            samsongGalaxy = 318.00;
            amount = samsongGalaxy * quantity;
      }
      else if (jchcSamsong.isSelected()&&selectedText.equals("Samsong Galaxy J2 SM-J200Y")){
            samsongGalaxy = 219.00;
            amount = samsongGalaxy * quantity;
      }
      else if (jchcSamsong.isSelected()&&selectedText.equals("Samsong Galaxy Note4 SM-N910F")){
            samsongGalaxy = 649.00;
            amount = samsongGalaxy * quantity;
      }
      else if (jchcSamsong.isSelected()&&selectedText.equals("Samsong Galaxy A3 SM-A300F")){
            samsongGalaxy = 289.00;
            amount = samsongGalaxy * quantity;
      }
      else if (jchcSamsong.isSelected()&&selectedText.equals("Samsong Galaxy J1 Ace")){
            samsongGalaxy = 119.00;
            amount = samsongGalaxy * quantity;
      }
      else if (jchcSamsong.isSelected()&&selectedText.equals("Samsong Galaxy A5 SM-A500F")){
            samsongGalaxy = 402.98;
            amount = samsongGalaxy * quantity;
      }
      else{
          amount = 0.00;
      }
      // code for Apple iphone
       String selectedText1 = (String)jcmbApple.getSelectedItem();
       String quantitySelected1 = (String)jcmbAppleQuantity.getSelectedItem();
      quantity1 = Integer.parseInt(quantitySelected1);
     
      if (jchcApple.isSelected()&&selectedText1.equals("Apple iphone 5s 16GB")){
            appleIphone = 499.00;
            amount1 = appleIphone * quantity1;
      }
      else if (jchcApple.isSelected()&&selectedText1.equals("Apple iphone 6s 64GB")){
          appleIphone = 1249.00;
          amount1 = appleIphone * quantity1;
      }
      else if (jchcApple.isSelected()&&selectedText1.equals("Apple iphone 5s 32GB")){
          appleIphone = 551.00;
          amount1 = appleIphone * quantity1;
      }
      else if (jchcApple.isSelected()&&selectedText1.equals("Apple iphone 6 16GB")){
          appleIphone = 799.00;
          amount1 = appleIphone * quantity1;
      }
      else if (jchcApple.isSelected()&&selectedText1.equals("Apple iphone 6s Plus 64GB")){
          appleIphone = 1429.00;
          amount1 = appleIphone * quantity1;
      }
      else if (jchcApple.isSelected()&&selectedText1.equals("Apple iphone 6 64GB")){
          appleIphone = 349.00;
          amount1 = appleIphone * quantity1;
      }
      else if (jchcApple.isSelected()&&selectedText1.equals("Apple iphone 6s 16GB")){
          appleIphone = 869.00;
          amount1 = appleIphone * quantity1;
      }
      else if (jchcApple.isSelected()&&selectedText1.equals("Apple iphone 5c 16GB")){
          appleIphone = 899.00;
          amount1 = appleIphone * quantity1;
      }
      else if (jchcApple.isSelected()&&selectedText1.equals("Apple iphone 6s 128GB")){
          appleIphone = 1409.00;
          amount1 = appleIphone * quantity1;
      }
      else if (jchcApple.isSelected()&&selectedText1.equals("Apple iphone Plus 16GB")){
          appleIphone = 899.00;
          amount1 = appleIphone * quantity1;
      }
      else{
          amount1 = 0.00;
      }
      //Nokia Lumia
      String selectedText2 = (String)jcmbNokia.getSelectedItem();
      String quantitySelected2 = (String)jcmbNokiaQuantity.getSelectedItem();
      quantity2 = Integer.parseInt(quantitySelected2);
     
     
      if (jchcNokia.isSelected()&&selectedText2.equals("Nokia Lumia 530")){
            nokiaLumia = 89.00;
            amount2 = nokiaLumia * quantity2;
      }
      else if (jchcNokia.isSelected()&&selectedText2.equals("Nokia Lumia 635")){
          nokiaLumia = 119.97;
          amount2 = nokiaLumia * quantity2;
      }
       else if (jchcNokia.isSelected()&&selectedText2.equals("Nokia Lumia 930")){
          nokiaLumia = 539.00;
          amount2 = nokiaLumia * quantity2;
      }
       else if (jchcNokia.isSelected()&&selectedText2.equals("Nokia Lumia 1020")){
          nokiaLumia = 500.00;
          amount2 = nokiaLumia * quantity2;
      }
       else{
           amount2 = 0.00;
       }
      // Sony Xperia
      String selectedText3 = (String)jcmbSony.getSelectedItem();
      String quantitySelected3 = (String)jcmbSonyQuantity.getSelectedItem();
      quantity3 = Integer.parseInt(quantitySelected3);
     
     
      if (jchcSony.isSelected()&&selectedText3.equals("Sony Xperia E4 E2105")){
            sonyPhone = 119.20;
            amount3 = sonyPhone * quantity3;
      }
       else if (jchcSony.isSelected()&&selectedText3.equals("Sony Xperia Z5 Premium")){
          sonyPhone = 989.00;
          amount3 = sonyPhone * quantity3;
      }
      else if (jchcSony.isSelected()&&selectedText3.equals("Sony Xperia E4 E2104")){
          sonyPhone = 147.00;
          amount3 = sonyPhone * quantity3;
      }
      else if (jchcSony.isSelected()&&selectedText3.equals("Sony Xperia 5 Dual E6683")){
          sonyPhone = 838.00;
          amount3 = sonyPhone * quantity3;
      }
      else if (jchcSony.isSelected()&&selectedText3.equals("Sony Xperia E4g E2003")){
          sonyPhone = 169.97;
          amount3 = sonyPhone * quantity3;
      }
      else if (jchcSony.isSelected()&&selectedText3.equals("Sony Xperia M4 Aqua")){
          sonyPhone = 350.98;
          amount3 = sonyPhone * quantity3;
      }
      else{
          amount3 = 0.00;
      }
      //LG Phone
      String selectedText4 = (String)jcmbLG.getSelectedItem();
      String quantitySelected4 = (String)jcmbLgQuantity.getSelectedItem();
      quantity4 = Integer.parseInt(quantitySelected4);
     
     
      if (jchcLG.isSelected()&&selectedText4.equals("LG G4 H815 Leather")){
            lgPhone = 549.00;
            amount4 = lgPhone * quantity4;
      }
      else if (jchcLG.isSelected()&&selectedText4.equals("LG G3 D855")){
          lgPhone = 405.00;
          amount4 = lgPhone * quantity4;
      }
      else if (jchcLG.isSelected()&&selectedText4.equals("LG G4 H815")){
          lgPhone = 549.00;
          amount4 = lgPhone * quantity4;
      }
      else if (jchcLG.isSelected()&&selectedText4.equals("LG G3 SD722")){
          lgPhone = 284.00;
          amount4 = lgPhone * quantity4;
      }
      else if (jchcLG.isSelected()&&selectedText4.equals("LG G4 Beat Dual H736P")){
          lgPhone = 289.98;
          amount4 = lgPhone * quantity4;
      }
      else if (jchcLG.isSelected()&&selectedText4.equals("LG G2 D802 16GB")){
          lgPhone = 329.00;
          amount4 = lgPhone * quantity4;
      }
      else if (jchcLG.isSelected()&&selectedText4.equals("LG V10 H962")){
          lgPhone = 929.00;
          amount4 = lgPhone * quantity4;
      }
      else{
          amount4 = 0.00;
      }
      subTotal = amount + amount1 + amount2 + amount3 + amount4;
      if (jchcSamsong.isSelected() || jchcApple.isSelected() || jchcSony.isSelected() || jchcLG.isSelected() || jchcNokia.isSelected()){
          tax = 8.0;
      }
      else{
          tax = 0.0;
      }
        total = subTotal + tax;
      if (jchcDiscount.isSelected()){
          
            discount = (total * 10)/100;
            fTotal = total - discount;
      }
      else{
          discount = 0.00;
          fTotal = total;
      }
      //Dispaly output result
      String result1 = Double.toString(discount);
      jtxtDiscount.setText(result1);
      
      String result2 = Double.toString(subTotal);
      jtxtSubTotal.setText(result2);
      
      String result3 = Double.toString(tax);
      jtxtTax.setText(result3);
      
      String result4 = Double.toString(fTotal);
      jtxtTotal.setText(result4);
      
      // Print receipt for the purchase phone and amount information
      //String txt1 = (String)jcmbLG.getSelectedItem();
      //String txt2 = (String)jcmbLgQuantity.getSelectedItem();
      if (jchcSamsong.isSelected() || jchcApple.isSelected() || jchcSony.isSelected() || jchcLG.isSelected() || jchcNokia.isSelected()){
    	  //To make sure that at least one is selected before printing receipt
      jtxtReceipt.append("====================GLOBAL MOBILE PHONE SHOPPING RECEIPT===================="+"\n");
      jtxtReceipt.append("\t"+"\t"+"\tDETAILS INFORMATION\n");
      jtxtReceipt.append("CUSTOMER NAME\t"+"\tEMAIL ADDRESS\n");
      String name = (String) jtxtName.getText();
      String name2 = (String) jtxtSecondName.getText();
      String email = (String) jtxtEmail.getText();
      jtxtReceipt.append(name+" "+name2+"\t"+"\t"+email+"\n"+"\n");
      jtxtReceipt.append("MOBILE PHONE\t"+"\tAMOUNT\t"+"\t"+"QUANTITY\t"+"\tMODEL\n");
      	if(jchcSamsong.isSelected()){
      		String text1 = (String)jcmbSamsong.getSelectedItem();
      		jtxtReceipt.append("Samsong Galaxy\t"+"\t"+samsongGalaxy+"\t"+"\t"+quantity+"\t"+"\t"+text1+"\n"); 
      	}
      	if(jchcApple.isSelected()){
      		String text2 = (String)jcmbApple.getSelectedItem();
      		jtxtReceipt.append("Apple iphone\t"+"\t"+appleIphone+"\t"+"\t"+quantity1+"\t"+"\t"+text2+"\n"); 
      	}
      	if(jchcNokia.isSelected()){
      		String text3 = (String)jcmbNokia.getSelectedItem();
      		jtxtReceipt.append("Nokia Lumia\t"+"\t"+nokiaLumia+"\t"+"\t"+quantity2+"\t"+"\t"+text3+"\n");
      	}
      	if(jchcSony.isSelected()){
      		String text4 = (String)jcmbSony.getSelectedItem();
      		jtxtReceipt.append("Sony Phone\t"+"\t"+sonyPhone+"\t"+"\t"+quantity3+"\t"+"\t"+text4+"\n");
      	}
      	if(jchcLG.isSelected()){
      		String text5 = (String)jcmbLG.getSelectedItem();
      		jtxtReceipt.append("Nokia Lumia\t"+"\t"+lgPhone+"\t"+"\t"+quantity4+"\t"+"\t"+text5+"\n"+"\n");
      	}
      	
      	jtxtReceipt.append("DISCOUNT\t"+"\tTAX\n");
      	jtxtReceipt.append(result1+"\t"+"\t"+"\t"+result3+"\n"+"\n");
      	
      	jtxtReceipt.append("SUB TOTAL\t"+"\tTOTAL"+"\n");
      	jtxtReceipt.append(result2+"\t"+"\t"+"\t"+result4+"\n");
      	
      	jtxtReceipt.append("====================THANK YOU FOR SHOPPING WITH US===================="+"\n");
      	jtxtReceipt.append("\t"+"\t"+"\t"+"Wishes you best enjoyment"+"\n");
      
      }
      // if not JtxtReceipt should be empty
      else{
    	  jtxtReceipt.append("");
    	  
      }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Return back to main menu
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        this.dispose();
    } 
    
    private void jButton4ActionPerform(java.awt.event.ActionEvent evt) {
    	// TODO Auto-generated method stub
    	//PrinterJob pj = PrinterJob.getPrinterJob();

    	// Initialize the Print Dialog with the number of pages in the document.
    	//PrintRequestAttributeSet attributes = new HashPrintRequestAttributeSet();
    	//attributes.add(new PageRanges(1, doc.getPageCount()));
    	//if (!pj.printDialog(attributes))
    	 //   return;
    	//AsposeWordsPrintDocument awPrintDoc = new AsposeWordsPrintDocument(doc);
    	// Pass our document as pageable to the printer job.
    	//pj.setPageable(awPrintDoc);
    	//PrintPreviewDialog previewDlg = new PrintPreviewDialog(awPrintDoc);
    	// Pass the desired page range attributes to the print preview dialog.
    	//previewDlg.setPrinterAttributes(attributes);

    	// Proceed with printing if the user accepts the print preview.
    	//if(previewDlg.display())
    	 //   pj.print(attributes);
    	
    	
    	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JCheckBox jchcApple;
    private javax.swing.JCheckBox jchcDiscount;
    private javax.swing.JCheckBox jchcLG;
    private javax.swing.JCheckBox jchcNokia;
    private javax.swing.JCheckBox jchcSamsong;
    private javax.swing.JCheckBox jchcSony;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jcmbApple;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jcmbAppleQuantity;
    private javax.swing.JComboBox jcmbLG;
    private javax.swing.JComboBox jcmbLgQuantity;
    private javax.swing.JComboBox jcmbNokia;
    private javax.swing.JComboBox jcmbNokiaQuantity;
    private javax.swing.JComboBox jcmbSamsonQuantity;
    private javax.swing.JComboBox jcmbSamsong;
    private javax.swing.JComboBox jcmbSony;
    private javax.swing.JComboBox jcmbSonyQuantity;
    private javax.swing.JTextArea jtxtAddress;
    private javax.swing.JTextField jtxtDiscount;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JComboBox jtxtGender;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPhone;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtSecondName;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration                   
}
